name: Auto

on:
  pull_request:
    branches:
      - develop
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{github.event.inputs.name}}!!!"